### ISSUE TITLE
medusa-config.ts or medusa-config.js

### ISSUE THREAD

**Issue by chillpilllike** [rokmohar/medusa-plugin-meilisearch#1]
Hello!

I do not find any file name medusa-config.js  to add the code and medusa-config.ts has different format.

kindly confirm where to add this code.

Thanks

**Comment by rokmohar** [comment]
You can put it in the medusa-config.ts under the plugins key of the exported config. It should be the same format of the exported config object.

**Comment by rokmohar** [comment]
Hey @chillpilllike

I've updated the README with the correct npm install command and updated medusa-config.ts

Please check it out and let me know how it works.

Thanks,
Rok
