### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by mnickkk** [rokmohar/medusa-plugin-meilisearch#2]
Seems like npm package is:

```
@rokmohar/medusa-plugin-meilisearch
```
 instead of:
```
npm install --save medusa-plugin-meilisearch
```
otherwise it installs an old, official version.

For me in order to resolve package I needed to:
```
module.exports = defineConfig({
  plugins: [
    {
      resolve: 'node_modules/@rokmohar/medusa-plugin-meilisearch',
```

Otherwise it throws:
```
info:    Skipping instrumentation registration. No register function found.
error:   Error starting server
error:   Unable to find the plugin "@rokmohar/medusa-plugin-meilisearch".
```

When subscription runs it thows:
```
warn:    An error occurred while processing product.product.updated: AwilixResolutionError: Could not resolve '@rokmohar/medusa-plugin-meilisearch'.

Resolution path: @rokmohar/medusa-plugin-meilisearch
warn:    One or more subscribers of product.product.updated failed. Retrying is not configured. Use 'attempts' option when emitting events.
```
Tried prepending node_modules to the path, but the resolve still fails

---

Great effort btw! Will update issue once I find a solution

**Comment by anwarpro** [comment]
Medusa 2.0 plugin system is broken. Use modules

**Comment by rokmohar** [comment]
Hey @mnickkk,

the exact configuration from README works for me. I use version 2.0.1.

It could be that your tsconfig is a bit different. Medusa tries to load plugins from node_modules, but you should not need to prepend the node_modules to it, it should load it from there automatically.

If you find a solution, please let me know, I will update the code and the README. I am really sorry I could not help you more here.

Thanks,
Rok

**Comment by rokmohar** [comment]
Hey @mnickkk

I've updated the README. I was writing so fast I did not notice that I did not update the package name. You need to run this command instead:

npm install --save @rokmohar/medusa-plugin-meilisearch

Please check the medusa-config.ts part, use modules and not plugins.

Let me know how it works for you.

Thanks,
Rok
