### ISSUE TITLE
Plugin or Module?

### ISSUE THREAD

**Issue by rpuls** [rokmohar/medusa-plugin-meilisearch#7]
Hi. Thank you for your work. I can't tell you how long I have waited for someone to break the ice on MeiliSearch for medusa 2.0. Thanks for doing it ;)

On your github Readme, you show config example in the `modules: []` list but on the npm page the exmaple shows the `plugins: []` list.

Which one should I use? 

Cheers!

**Comment by rokmohar** [comment]
Hello,

Please use the `modules`, I will publish a new version with updated README on npm page.

Regards

**Comment by rpuls** [comment]
Thanks man ! :)

**Comment by SalahAdDin** [comment]
> Hello,
> 
> Please use the `modules`, I will publish a new version with updated README on npm page.
> 
> Regards

It still uses plugins.
